INSERT INTO JobPostings (Title, Description, Department, Status, CreatedAt) VALUES
(N'Sistem Yöneticisi', N'Linux sunucuların yönetimi, bakım ve güncellemelerinden sorumlu takım arkadaşı.', N'Bilgi İşlem', N'Açık', GETDATE()),
(N'Frontend Geliştirici (React)', N'Modern web teknolojileriyle kullanıcı dostu arayüzler tasarlayacak geliştirici.', N'Yazılım', N'Açık', GETDATE()),
(N'Backend Developer (C#)', N'.NET Core teknolojilerinde deneyimli, mikroservis mimarisine hakim mühendis.', N'Yazılım', N'Açık', GETDATE()),
(N'İnsan Kaynakları Uzmanı', N'İşe alım süreçlerini yönetecek ve personel özlük dosyalarını takip edecek uzman.', N'İnsan Kaynakları', N'Açık', GETDATE()),
(N'Veri Bilimcisi', N'Büyük veri analizi yapıp, makine öğrenimi modelleri eğitecek veri bilimci arıyoruz.', N'Veri & Analitik', N'Açık', GETDATE()),
(N'Siber Güvenlik Analisti', N'Sistem zaafiyetlerini bulup, güvenlik duvarı ve siber tehditleri yönetecek analist.', N'Güvenlik', N'Açık', GETDATE()),
(N'Proje Yöneticisi', N'Çevik (Agile) yöntemlerle yazılım projelerini baştan sona yönetecek lider.', N'Proje Yönetimi', N'Açık', GETDATE()),
(N'Mobil Uygulama Geliştirici', N'Flutter veya React Native kullanarak çapraz platform mobil uygulamalar geliştirecek.', N'Yazılım', N'Açık', GETDATE()),
(N'UI/UX Tasarımcısı', N'Kullanıcı deneyimini merkeze alarak modern arayüzler tasarlayacak yaratıcı.', N'Tasarım', N'Açık', GETDATE()),
(N'DevOps Mühendisi', N'CI/CD süreçlerini otomatize edip Docker/K8s mimarilerini yönetecek mühendis.', N'Altyapı', N'Açık', GETDATE()),
(N'Kurumsal İletişim Uzmanı', N'Şirket içi ve dışı iletişim stratejilerini belirleyip PR kampanyaları yürütecek.', N'Pazarlama', N'Açık', GETDATE()),
(N'Dijital Pazarlama Uzmanı', N'SEO, SEM ve sosyal medya reklam kampanyalarını verilerle ölçecek ve yönetecek.', N'Pazarlama', N'Açık', GETDATE()),
(N'Veritabanı Yöneticisi (DBA)', N'MS SQL ve PostgreSQL sunucularının performansı ve güvenliğinden sorumlu yönetici.', N'Veritabanı', N'Açık', GETDATE()),
(N'QA Test Mühendisi', N'Yazılım ürünlerinde manuel ve otomatize (Selenium) testler yazacak kalite kontrolcü.', N'Yazılım', N'Açık', GETDATE()),
(N'Müşteri Temsilcisi', N'Gelen müşteri çağrılarını yanıtlayıp çözüm üretecek problem çözme yeteneğine sahip arkadaş.', N'Müşteri Hizmetleri', N'Açık', GETDATE()),
(N'Oyun Geliştirici (Unity)', N'C# diline hakim ve Unity motorunda mobil oyunlar geliştirebilecek deneyimli yazılımcı.', N'Yazılım', N'Açık', GETDATE()),
(N'Yapay Zeka Mühendisi', N'Derin öğrenme modelleri ve LLM entegrasyonları üzerinde çalışacak AI uzmanı.', N'Ar-Ge', N'Açık', GETDATE()),
(N'Satış Danışmanı', N'Şirketin ürün ve hizmetlerini kurumsal müşterilere (B2B) tanıtıp satış kapatacak.', N'Satış', N'Açık', GETDATE()),
(N'Finans Analisti', N'Mali tabloları analiz edip nakit akışı raporlamalarını hazırlayacak finans uzmanı.', N'Muhasebe & Finans', N'Açık', GETDATE()),
(N'Sosyal Medya Yöneticisi', N'Markanın tüm sosyal medya hesapları için içerik üretecek ve topluluk yönetecek.', N'Pazarlama', N'Açık', GETDATE()),
(N'Destek Mühendisi (L2)', N'Müşterilerden gelen teknik sorunları inceleyip anında müdahale edecek destek uzmanı.', N'IT Destek', N'Açık', GETDATE()),
(N'Muhasebe Uzmanı', N'Günlük fatura girişi, banka mutabakatları ve cari hesap takibini üstlenecek takım arkadaşı.', N'Muhasebe', N'Açık', GETDATE()),
(N'İş Analisti', N'Müşteri gereksinimlerini toplayıp teknik ekiplere analiz dokümanı hazırlayacak yetenek.', N'Proje Yönetimi', N'Açık', GETDATE()),
(N'Network Uzmanı', N'Ağ yapılandırması, Switch/Router kurulumu ve VPN tünel yönetimini yapabilecek.', N'Bilgi İşlem', N'Açık', GETDATE()),
(N'İçerik Editörü', N'Blog, SEO ve e-ticaret sitelerimiz için özgün ve kaliteli SEO uyumlu metinler üretecek.', N'Pazarlama', N'Açık', GETDATE()),
(N'E-Ticaret Yöneticisi', N'Sitenin kampanya süreçlerini, stok durumunu ve satış dönüşüm oranlarını yönetecek.', N'E-Ticaret', N'Açık', GETDATE()),
(N'Bilgi Güvenliği Uzmanı', N'ISO 27001 ve KVKK denetimlerini yürütüp şirketin bilgi güvenliğini koruyacak yetkili.', N'Hukuk & İnsan Kaynakları', N'Açık', GETDATE()),
(N'Kıdemli Sistem Mimarı', N'Yüksek trafikli sunucu altyapılarını sıfırdan dizayn edecek deneyimli mimar.', N'Altyapı', N'Açık', GETDATE()),
(N'SEO Uzmanı', N'Web sitemizin organik arama motoru trafiğini artırmak için anahtar kelime ve backlink çalışmaları yapacak.', N'Pazarlama', N'Açık', GETDATE()),
(N'Otomotiv Mühendisi', N'Yenilikçi ar-ge projelerimizde simülasyon ve araç sistem mühendisliğini yönetecek.', N'Mühendislik', N'Açık', GETDATE()),
(N'Endüstri Mühendisi', N'Üretim süreçlerinde verimlilik analizi yapıp yalın üretim prensiplerini uygulayacak.', N'Üretim', N'Açık', GETDATE()),
(N'Makine Öğrenimi Araştırmacısı', N'Teorik algoritmaları pratik iş problemlerine uygulayarak şirketin veri altyapısını geliştirecek.', N'Ar-Ge', N'Açık', GETDATE()),
(N'Halkla İlişkiler Sorumlusu', N'Etkinlik yönetimi, basın bülteni hazırlama ve dış ilişkiler ofisi temsilciliği.', N'PR', N'Açık', GETDATE()),
(N'Bölge Satış Müdürü', N'İlgili bölgede bayi ağını genişletecek ve satış hedeflerine liderlik edecek.', N'Satış', N'Açık', GETDATE()),
(N'Satın Alma Uzmanı', N'Kurum içi ihtiyaçların fiyat araştırma, tedarik ve sözleşme süreçlerini yürütecek.', N'Satın Alma', N'Açık', GETDATE()),
(N'İdari İşler Şefi', N'Şirketin ofis yönetimi, araç filosu ve bina güvenlik süreçlerinden sorumlu yönetici.', N'İdari İşler', N'Açık', GETDATE()),
(N'Full Stack Developer (MERN)', N'MongoDB, Express, React, Node.js yığınına tamamen hakim yetenekli geliştirici.', N'Yazılım', N'Açık', GETDATE()),
(N'Performans Pazarlama Yöneticisi', N'Google Ads, Meta Ads ve Tiktok bütçelerini yönetecek yüksek performans arayan lider.', N'Pazarlama', N'Açık', GETDATE()),
(N'Webmaster', N'Kurumsal sitelerin cPanel/Plesk üzerinden barındırma ve küçük görsel güncellemelerini yürütecek.', N'IT Destek', N'Açık', GETDATE()),
(N'Bulut (Cloud) Mimarı', N'AWS / Azure teknolojilerinde sertifikalı ve devasa sunucu geçişlerini yönetecek uzman.', N'Altyapı', N'Açık', GETDATE()),
(N'Oyun Tasarımcısı (Game Designer)', N'Oyunların bölüm tasarımlarını, mekaniklerini ve ekonomi döngüsünü modelleyecek tasarımcı.', N'Tasarım', N'Açık', GETDATE()),
(N'Veri Giriş Uzmanı', N'Geçmiş arşivdeki evrakları büyük bir dikkat ve hızla dijital sisteme aktaracak.', N'Operasyon', N'Açık', GETDATE()),
(N'Lojistik Operasyon Uzmanı', N'Uluslararası taşımacılık belgelerini düzenleyip nakliye takibini gerçekleştirecek.', N'Lojistik', N'Açık', GETDATE()),
(N'Çevirmen (İngilizce & Almanca)', N'Yabancı müşterilerle toplantılarda simültane çeviri ve resmi yazışmaları yürütecek.', N'Çeviri', N'Açık', GETDATE()),
(N'Hukuk Danışmanı', N'Ticaret hukuku, sözleşmeler ve KVKK uyumluluk metinlerini yasal düzlemde onaylayacak.', N'Hukuk', N'Açık', GETDATE()),
(N'Depo Sorumlusu', N'Gelen ve giden ürünlerin sayımını yapıp, depo içi istiflemeden sorumlu takım arkadaşı.', N'Lojistik', N'Açık', GETDATE()),
(N'Motion Graphics Designer', N'After Effects, Premiere kullanarak sosyal medya reklamları ve kısa animasyonlar üretecek.', N'Tasarım', N'Açık', GETDATE()),
(N'İhracat Müdürü', N'Uluslararası pazarlarda yeni müşteriler bulup yurt dışı satış stratejilerini kurgulayacak lider.', N'Satış', N'Açık', GETDATE()),
(N'Kalite Yönetim Temsilcisi', N'ISO 9001 standartlarının şirkette uygulanması ve şirket içi denetimlerin organize edilmesi.', N'Kalite', N'Açık', GETDATE()),
(N'İş Geliştirme Uzmanı', N'Şirkete yeni gelir modelleri katacak partnerlik görüşmeleri ve sektör analizi yapacak uzman.', N'İş Geliştirme', N'Açık', GETDATE());
